### ISSUE TITLE
'flutter packages get' always not responding.

### ISSUE THREAD

**Issue by arden** [davidmarne/built_redux#69] opened 2018-04-25 13:12 UTC
when i'm use built_redux, and flutter packages get, it's always not responding.

i'm use flutter 3.1 beta.

**Comment by davidmarne** [comment] 2018-04-25 22:52
I can try out flutter 3.1 tonight and see if I can reproduce. In the meantime would you please post your pubspec.yaml?

**Comment by davidmarne** [comment] 2018-04-26 02:29
Seems to work just fine fore me.
If you are using dart 2 check out the [dart-2-dev](https://github.com/davidmarne/built_redux/tree/dart-2-dev) branch and make sure that you have:
`built_redux: ^7.4.1-dev` in your pubspec.yaml and not `built_redux: ^7.4.1`

**Comment by zoechi** [comment] 2018-04-26 07:30
I think it should be `built_redux: 7.4.1-dev` without `^`
`^7.4.1-dev` means `7.4.1-dev` and all later versions that are not considered breaking (same major version)
`7.4.1` is a later version than `7.4.1-dev` (because `-` makes it a pre-release version)
This is why I commented that `7.4.1-dev` should have been released as `7.5.0-dev`

**Comment by davidmarne** [comment] 2018-04-26 14:33
Yeah I see what you mean now @zoechi, I can start publishing the dev line one patch ahead of the stable line

**Comment by zoechi** [comment] 2018-07-11 16:06
@davidmarne built_redux 7.4.2 still doesn't work with build ^0.12.0?

**Comment by davidmarne** [comment] 2018-09-13 04:32
missed that last comment sorry, it does now. gonna close this

**Closed by davidmarne** 2018-09-13 04:32 UTC

**Comment by zoechi** [comment] 2018-09-13 05:32
Working great now anyway. Thanks 👍
