### ISSUE TITLE
Redux Generator is omitting the complex type information (such as repatch)

### ISSUE THREAD

**Issue by sclee15** [davidmarne/built_redux#55] opened 2018-02-02 13:20 UTC
this action

abstract class TopStateAction extends ReduxActions {
  ActionDispatcher<Repatch<TopState, TopStateBuilder>> repatchDispatcher;

  TopStateAction._();
  factory TopStateAction() => new _$TopStateAction();
}

is converted to

 class _$TopStateAction extends TopStateAction{
    factory _$TopStateAction() => new _$TopStateAction._();
    _$TopStateAction._() : super._();

    final ActionDispatcher< **null**<TopState,TopStateBuilder> > repatchDispatcher = new ActionDispatcher<**null**<TopState,TopStateBuilder>>('TopStateAction-repatchDispatcher');

    @override
    void setDispatcher(Dispatcher dispatcher) {
      repatchDispatcher.setDispatcher(dispatcher);
    }
  }

the type in actiondispather in the generated part file should not be null instead the Repatch

I tested in Dart 2.0 in Dev channel.

**Comment by davidmarne** [comment] 2018-02-03 19:38
That's really weird, especially since it generated the generic types of the repatch correctly. 
I don't have a whole lot of ideas unfortunately...
I tried generating [this](https://github.com/davidmarne/built_redux_repatch/blob/master/test/unit/test_counter.dart) test file from the repatch repo with dart 2.0.0-dev.20.0 and 1.24.3 and it worked just fine...

I tested with:
built_redux: 7.3.5
build_runnder: 0.6.0+1
build: 0.11.1

What versions do you have in your pubspec.lock for those dependencies?

**Comment by sclee15** [comment] 2018-02-05 01:31
I build a test file and it is same

build_runner: 0.7.5+1
build: 0.11.2
built_redux: 7.3.5
Dart VM version: 2.0.0-dev.19.0 (Fri Jan 19 08:01:12 2018 +0100) on "macos_x64"

**Comment by davidmarne** [comment] 2018-02-06 04:03
Alright, well I'm not quite sure. I have not tried build_runner 0.7.x yet, so I am curious, what does your build script look like? Are your trying to use `pub run build_runner build`?
Also, what versions do you have pinned for source_gen and analyzer? My best bet to try and reproduce is to get to all of the same dependencies as you.

For what its worth it might be worth staying with build_runner 0.6.x until there is more support for 0.7.x from built_value. Looks like david morgan is working on a pr here: https://github.com/google/built_value.dart/pull/342
I will make a PR to built_redux to follow the same patterns shortly after his gets merged.

**Comment by davidmarne** [comment] 2018-04-26 02:31
Closing as this is stale and I cannot reproduce

**Closed by davidmarne** 2018-04-26 02:31 UTC
